[project]
name = "black-hat-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7.5"
dependencies = [
    "lxml>=5.4.0",
    "opencv-python>=4.13.0.90",
    "paramiko>=3.5.1",
    "scapy>=2.7.0",
]
